name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build the image
        run: |
          docker build -t ghcr.io/sundeepchand/hello-node:latest .
          docker push ghcr.io/sundeepchand/hello-node:latest